import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>HVAR - WHIRLPOOL | TECHNICAL CHALLENGE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>hello world</h1>
    </div>
  );
}
